#!/usr/bin/python

# This program is placed under the GPL license.
# Copyright (c) 2016, Emlid Limited
# All rights reserved.

# If you are interested in using this program as a part of a
# closed source project, please contact Emlid Limited (info@emlid.com).

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from reachled import LEDService


if __name__ == "__main__":
    LEDService().run()
